version: "3.8"

services:
  frontend:
    build:
      context: ./VulLink-Visualizer
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
        REACT_APP_NEO4J_URL: ${REACT_APP_NEO4J_URL}
        REACT_APP_NEO4J_USER: ${REACT_APP_NEO4J_USER}
        REACT_APP_NEO4J_PASSWORD: ${REACT_APP_NEO4J_PASSWORD}
    container_name: vullink-frontend
    ports:
      - "80:80"
    env_file:
      - ./VulLink-Visualizer/.env
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./VulLink-API
    container_name: vullink-backend
    ports:
      - "8000:8000"
    env_file:
      - ./VulLink-API/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped